name: Deploy Customer Azure Enterprise Scale Landing Zone
on:
  push:
      branches: [ main ]
  workflow_dispatch:


jobs:
  
  deploy-RG:
    uses: ./.github/workflows/1-pnk-reourcegroups.yml
    with:
      az_powershell_min_version: ${{ vars.AZ_POWERSHELL_MIN_VERSION }}
      Subscription_Id: 'a1c49950-1900-406e-8f64-09ab4e0fc86a'
    secrets: inherit
