name: Deploy VNET

on:
  workflow_call:
    inputs:
      Top_Management_Group_Id:
        required: true
        type: string

jobs:
  deploy-diagnostic-settings:
    runs-on: [self-hosted, linux]
    
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        name: Azure OIDC login
        with:         
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - uses: azure/arm-deploy@v1 
        name: Deploy custom RBAC role definitions
        id: customRbacRoleDefinitions
        with:
          scope: resourcegroup
          region: westeurope
          resourceGroupName: ${{ steps.resourceGroupLogging.outputs.resourceGroupName }}
          template: modules\hubNetworking\parameters\hubNetworking.parameters.all.json
          parameters: modules/logging/parameters/logging.parameters.all.json
