name: Deploy VNET

on:
  workflow_call:
    inputs:
      Top_Management_Group_Id:
        required: true
        type: string

jobs:
  deploy-VNET:
    runs-on: [self-hosted, linux]
    
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        name: Azure OIDC login
        with:         
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - uses: azure/arm-deploy@v1
        name: Create the Resource Group for VNET
        id: resourceGroupVNET
        with:
          scope: subscription
          region: westeurope
          subscriptionId: ${{ inputs.Subscription_Id }}
          template: ARMtemplates/resourceGroup.json
          parameters: modules\hubNetworking\parameters\resourceGroup.parameters.json

      - uses: azure/arm-deploy@v1 
        name: Deploy custom RBAC role definitions
        id: customRbacRoleDefinitions
        with:
          scope: resourcegroup
          region: westeurope
          resourceGroupName: ${{ steps.resourceGroupVNET.outputs.resourceGroupName }}
          template: modules\hubNetworking\parameters\hubNetworking.bicep
          parameters: modules\hubNetworking\parameters\hubNetworking.parameters.all.json
