name: Deploy Azure Enterprise Scale Landing Zone
on:
  push:
      branches: [ main ]
  workflow_dispatch:
  
jobs:
  deploy-management-groups:
    uses: ./.github/workflows/managementgroups.yaml
    with: 
      az_powershell_min_version: ${{ vars.AZ_POWERSHELL_MIN_VERSION }}
    secrets: inherit